allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-brand@0.2.0-rc.2'
  - '@deepseek-ai/dsh-http-proxy@0.2.0-rc.2'
  - '@deepseek-ai/dsh-llm@0.2.0-rc.2'
  - '@deepseek-ai/dsh-timeout@0.2.0-rc.2'
  - '@deepseek-ai/dsh-typert-protocol@0.2.0-rc.2'
  - '@deepseek-ai/dsh-util-crypto@0.2.0-rc.2'
  - '@deepseek-ai/dsh-util-values@0.2.0-rc.2'
  - '@deepseek-ai/dsh-web-fetch-http@0.2.0-rc.2'
  - '@deepseek-ai/dsh-web@0.2.0-rc.2'
